# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "lts-linux-firmware-mixin"
BBFILE_PATTERN_lts-linux-firmware-mixin = "^${LAYERDIR}/"
# Use the same priority as OE-Core so that DEFAULT_PREFERENCE works
BBFILE_PRIORITY_lts-linux-firmware-mixin = "5"

LAYERSERIES_COMPAT_lts-linux-firmware-mixin = "wrynose"

LAYERDEPENDS_lts-linux-firmware-mixin = " \
    core \
"

# https://git.openembedded.org/openembedded-core/commit/?id=2b75c7ba5e3aa6fc57d7b4afe59e2277b4d87de1
firmwaredir = "${nonarch_base_libdir}/firmware"
